/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

export default function BearDab(props) {
    const groupRef = useRef();
    const { nodes, materials } = useGLTF("./models/dabPose.gltf");

    useFrame(() => {
        groupRef.current.rotation.y += 0.01
    })

    return (
        <group {...props} dispose={null} ref={groupRef}>
            <mesh
                name="body001"
                castShadow
                receiveShadow
                geometry={nodes.body001.geometry}
                material={materials.Body}
                morphTargetDictionary={nodes.body001.morphTargetDictionary}
                morphTargetInfluences={nodes.body001.morphTargetInfluences}
                position={[0, 1.306, 0]}
            />
            <mesh
                name="Jacket001"
                castShadow
                receiveShadow
                geometry={nodes.Jacket001.geometry}
                material={materials.Jacket}
                morphTargetDictionary={nodes.Jacket001.morphTargetDictionary}
                morphTargetInfluences={nodes.Jacket001.morphTargetInfluences}
                position={[0, 1.306, 0]}
            />
            <mesh
                name="pants001"
                castShadow
                receiveShadow
                geometry={nodes.pants001.geometry}
                material={materials.pants}
                morphTargetDictionary={nodes.pants001.morphTargetDictionary}
                morphTargetInfluences={nodes.pants001.morphTargetInfluences}
                position={[0, 1.306, 0]}
            />
            <mesh
                name="Shirt001"
                castShadow
                receiveShadow
                geometry={nodes.Shirt001.geometry}
                material={materials.Shirt}
                morphTargetDictionary={nodes.Shirt001.morphTargetDictionary}
                morphTargetInfluences={nodes.Shirt001.morphTargetInfluences}
                position={[0, 1.306, 0]}
            />
            <primitive object={nodes.Hips} />
        </group>
    );
}

useGLTF.preload("./models/dabPose.gltf");
