/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

export default function BearSurprise(props) {
    const groupRef = useRef();
    const { nodes, materials } = useGLTF("./models/surprisedPose.gltf");

    useFrame(() => {
        groupRef.current.rotation.y += 0.01
    })
    return (
        <group {...props} dispose={null} ref={groupRef}>
            <mesh
                name="body001"
                castShadow
                receiveShadow
                geometry={nodes.body001.geometry}
                material={materials["Body.002"]}
                morphTargetDictionary={nodes.body001.morphTargetDictionary}
                morphTargetInfluences={nodes.body001.morphTargetInfluences}
                position={[0, 1.306, 0]}
            />
            <mesh
                name="Jacket001"
                castShadow
                receiveShadow
                geometry={nodes.Jacket001.geometry}
                material={materials["Jacket.002"]}
                morphTargetDictionary={nodes.Jacket001.morphTargetDictionary}
                morphTargetInfluences={nodes.Jacket001.morphTargetInfluences}
                position={[0, 1.306, 0]}
            />
            <mesh
                name="pants001"
                castShadow
                receiveShadow
                geometry={nodes.pants001.geometry}
                material={materials["pants.002"]}
                morphTargetDictionary={nodes.pants001.morphTargetDictionary}
                morphTargetInfluences={nodes.pants001.morphTargetInfluences}
                position={[0, 1.306, 0]}
            />
            <mesh
                name="Shirt001"
                castShadow
                receiveShadow
                geometry={nodes.Shirt001.geometry}
                material={materials["Shirt.002"]}
                morphTargetDictionary={nodes.Shirt001.morphTargetDictionary}
                morphTargetInfluences={nodes.Shirt001.morphTargetInfluences}
                position={[0, 1.306, 0]}
            />
            <group position={[0, 0.711, 0]}>
                <group position={[0, 0.177, 0]}>
                    <group position={[0, 0.192, 0]}>
                        <group position={[0, 0.221, 0]}>
                            <group position={[0, 0.2, 0]}>
                                <group position={[0, 0.168, 0]} scale={0.344}>
                                    <mesh
                                        name="Cube019"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cube019.geometry}
                                        material={materials["Head.004"]}
                                        morphTargetDictionary={
                                            nodes.Cube019.morphTargetDictionary
                                        }
                                        morphTargetInfluences={
                                            nodes.Cube019.morphTargetInfluences
                                        }
                                    />
                                    <mesh
                                        name="Cube019_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cube019_1.geometry}
                                        material={materials["Head.005"]}
                                        morphTargetDictionary={
                                            nodes.Cube019_1
                                                .morphTargetDictionary
                                        }
                                        morphTargetInfluences={
                                            nodes.Cube019_1
                                                .morphTargetInfluences
                                        }
                                    />
                                    <mesh
                                        name="Cube019_2"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cube019_2.geometry}
                                        material={materials["Mouth.002"]}
                                        morphTargetDictionary={
                                            nodes.Cube019_2
                                                .morphTargetDictionary
                                        }
                                        morphTargetInfluences={
                                            nodes.Cube019_2
                                                .morphTargetInfluences
                                        }
                                    />
                                    <mesh
                                        name="Cube019_3"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cube019_3.geometry}
                                        material={materials["Eye.002"]}
                                        morphTargetDictionary={
                                            nodes.Cube019_3
                                                .morphTargetDictionary
                                        }
                                        morphTargetInfluences={
                                            nodes.Cube019_3
                                                .morphTargetInfluences
                                        }
                                    />
                                    <mesh
                                        name="Cube019_4"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cube019_4.geometry}
                                        material={materials["Material.003"]}
                                        morphTargetDictionary={
                                            nodes.Cube019_4
                                                .morphTargetDictionary
                                        }
                                        morphTargetInfluences={
                                            nodes.Cube019_4
                                                .morphTargetInfluences
                                        }
                                    />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("./models/surprisedPose.gltf");
