/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useFrame } from "@react-three/fiber";
import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function BearGross(props) {
    const groupRef = useRef();
    const { nodes, materials } = useGLTF("./models/bearGross10-9-24.gltf");
    
    useFrame(() => {
        groupRef.current.rotation.y += 0.01;
    })
    
    return (
        <group {...props} dispose={null} ref={groupRef}>
            <group position={[0, 1.67, 0]} scale={0.344}>
                <mesh
                    name="Cube002"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube002.geometry}
                    material={materials["Material.004"]}
                    morphTargetDictionary={nodes.Cube002.morphTargetDictionary}
                    morphTargetInfluences={nodes.Cube002.morphTargetInfluences}
                />
                <mesh
                    name="Cube002_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube002_1.geometry}
                    material={materials.EverythingElse}
                    morphTargetDictionary={
                        nodes.Cube002_1.morphTargetDictionary
                    }
                    morphTargetInfluences={
                        nodes.Cube002_1.morphTargetInfluences
                    }
                />
                <mesh
                    name="Cube002_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube002_2.geometry}
                    material={materials.Material}
                    morphTargetDictionary={
                        nodes.Cube002_2.morphTargetDictionary
                    }
                    morphTargetInfluences={
                        nodes.Cube002_2.morphTargetInfluences
                    }
                />
            </group>
        </group>
    );
}

useGLTF.preload("/bearGross10-9-24.gltf");
