/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useFrame } from "@react-three/fiber"
import { useGLTF } from "@react-three/drei";

export default function ModelDefault(props) {
    const groupRef = useRef();
    const { nodes, materials } = useGLTF("/models/bearStandPaw.gltf");
    
    useFrame(() => {
        groupRef.current.rotation.y += 0.01
    })
    return (
        <group {...props} dispose={null} ref={groupRef}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.beard.geometry}
                material={materials.Head}
                position={[0, 1.663, 0]}
                scale={0.344}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.body.geometry}
                material={materials.Body}
                position={[0, 1.306, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ears.geometry}
                material={materials["Head.001"]}
                position={[0, 1.112, 0]}
                rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Eyebrow.geometry}
                material={materials["Material.002"]}
                position={[0, 1.67, 0]}
                scale={0.344}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.head.geometry}
                material={materials.Head}
                position={[0, 1.67, 0]}
                scale={0.344}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.headfluffs.geometry}
                material={materials.Head}
                position={[0, 1.877, 0]}
                rotation={[0, Math.PI / 2, 0]}
                scale={0.279}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Jacket.geometry}
                material={materials.Jacket}
                position={[0, 1.306, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.pants.geometry}
                material={materials.pants}
                position={[0, 1.306, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.pupils.geometry}
                material={materials.Eye}
                position={[0, 1.112, 0]}
                scale={0.554}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Shirt.geometry}
                material={materials.Shirt}
                position={[0, 1.306, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Bottom_Teeth.geometry}
                material={materials.Mouth}
                position={[-0.001, 1.556, 0.115]}
                rotation={[2.87, 0.009, -2.967]}
                scale={[-0.101, -0.011, -0.101]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.tongue.geometry}
                material={materials.Mouth}
                position={[0.031, 1.663, -0.147]}
                rotation={[-0.251, -0.012, -0.174]}
                scale={0.344}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Top_Teeth.geometry}
                material={materials.Mouth}
                position={[0.008, 1.607, 0.101]}
                rotation={[-0.271, -0.009, -0.174]}
                scale={[0.101, 0.011, 0.101]}
            />
        </group>
    );
}

useGLTF.preload("/models/bearStandPaw.gltf");
